name: kanji

services:
  web:
    build: .
    container_name: kanji
    command: >
      bash -c " rm -f tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0 -p 3000"
    ports:
      - 3000:3000
    env_file:
      - ./.env
    volumes:
      - .:/src/app
      - /app/tmp
      - bundle-data:/usr/local/bundle
    depends_on:
      - db
    links:
      - db:db
    stdin_open: true
    tty: true
  db:
    image: mysql:5.7.30
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kanji_development
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3310:3306"
    container_name: kanji.database
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    command: redis-server
    container_name: kanji.redis
    volumes:
      - redis-data:/var/shared/redis
  sidekiq:
    build: .
    command: bundle exec sidekiq -C ./config/sidekiq.yml 2>&1 | tee ./log/sidekiq.log
    container_name: kanji.sidekiq
    volumes:
      - .:/src/app
    links:
      - db
      - redis
    stdin_open: true
    tty: true
volumes:
  mysql_data:
  bundle-data:
  redis-data:
