default: &default
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_unicode_ci
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: <%= ENV['KANJI_DATABASE_PASSWORD'] %>
  port: <%= ENV.fetch("DB_PORT") { 3306 } %>
  host: <%= ENV.fetch("KANJI_HOST", "db") %>

development:
  primary:
    <<: *default
    username: <%= ENV.fetch("DB_USER") { "root" } %>
    database: kanji_development

test:
  primary:
    <<: *default
    username: <%= ENV.fetch("DB_USER") { "root" } %>
    database: kanji_test

staging:
  primary:
    <<: *default
    host: <%= ENV['DB_HOST'] %>
    database: kanji_staging
    username: <%= ENV.fetch("DB_USER") { "kanji" } %>

production:
  primary:
    <<: *default
    host: <%= ENV['DB_HOST'] %>
    database: kanji_production
    username: <%= ENV.fetch("DB_USER") { "kanji" } %>
